---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: node-feature-discovery
    repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    version: 0.2.1
    releaseName: node-feature-discovery
    namespace: node-feature-discovery
    valuesFile: values.yaml
