---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: cloudflare-tunnel
    repo: https://cloudflare.github.io/helm-charts
    version: 0.3.0
    releaseName: cloudflare-tunnel
    namespace: cloudflare
    valuesFile: values.yaml
