---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mqtt
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/dudo/homelab.git
    targetRevision: HEAD
    path: infrastructure/mqtt/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: zilla
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
