---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homebridge
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/dudo/homelab.git
    targetRevision: HEAD
    path: applications/homebridge/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: home
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
