---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: tetragon
    repo: https://helm.cilium.io
    version: 1.0.0
    releaseName: tetragon
    namespace: kube-system
    valuesFile: values.yaml
