---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/dudo/homelab.git
    targetRevision: HEAD
    path: infrastructure/system-upgrade-controller/overlays/local
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
